import pg from 'pg';

const { Client } = pg;

const SQL = `
create table if not exists public.pieces (
  id          text primary key,
  brand       text not null,
  name        text not null,
  cat         text not null,
  size        text not null,
  condition   text not null,
  price       numeric(10,2) not null,
  image_url   text,
  status      text not null default 'disponivel',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.pieces add column if not exists status text not null default 'disponivel';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'pieces_status_check'
  ) then
    alter table public.pieces
      add constraint pieces_status_check check (status in ('disponivel', 'indisponivel'));
  end if;
end $$;

alter table public.pieces enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'pieces' and policyname = 'pieces_public_read'
  ) then
    create policy "pieces_public_read" on public.pieces for select using (true);
  end if;
end $$;

create table if not exists public.piece_images (
  id            bigint generated by default as identity primary key,
  piece_id      text not null references public.pieces(id) on delete cascade,
  storage_path  text not null unique,
  url           text not null,
  created_at    timestamptz not null default now()
);

create index if not exists piece_images_piece_id_idx on public.piece_images (piece_id);

alter table public.piece_images enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'piece_images' and policyname = 'piece_images_public_read'
  ) then
    create policy "piece_images_public_read" on public.piece_images for select using (true);
  end if;
end $$;

alter table public.piece_images add column if not exists position integer not null default 0;

with groups_to_backfill as (
  select piece_id
  from public.piece_images
  group by piece_id
  having count(*) > 1 and max(position) = 0
),
ranked as (
  select id, row_number() over (partition by piece_id order by created_at, id) - 1 as rn
  from public.piece_images
  where piece_id in (select piece_id from groups_to_backfill)
)
update public.piece_images pi
set position = ranked.rn
from ranked
where pi.id = ranked.id;
`;

const client = new Client({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false }
});

await client.connect();
try {
  await client.query(SQL);
  console.log('Migração ok: tabelas "pieces" e "piece_images" prontas.');
} finally {
  await client.end();
}
